flags: {}

#resolver: lts-6.6
#compiler: ghcjs-0.2.0.900006006_ghc-7.10.3
#compiler-check: match-exact

#setup-info:
#ghcjs:
#    source:
#      ghcjs-0.2.0.900006006_ghc-7.10.3:
#         url: "https://tolysz.org/ghcjs/lts-6.6-900006006.tar.gz"
# allow-newer: true

# https://docs.haskellstack.org/en/stable/ghcjs/
resolver: lts-7.19
compiler: ghcjs-0.2.1.9007019_ghc-8.0.1
compiler-check: match-exact

setup-info:
  ghcjs:
    source:
      ghcjs-0.2.1.9007019_ghc-8.0.1:
           url: http://ghcjs.tolysz.org/ghc-8.0-2017-02-05-lts-7.19-9007019.tar.gz
           sha1: d2cfc25f9cda32a25a87d9af68891b2186ee52f9
#           url: "http://tolysz.org/ghcjs/untested/ghc-8.0-2017-03-23-lts-8.5-9008005.tar.gz"
#           sha1: cd1d764d839e0af260eb6867a533f544ff451862
allow-newer: true

#resolver: lts-8.5
#compiler: ghcjs-0.2.0.820170320_ghc-8.0.1
#compiler: ghcjs-master
#compiler: ghcjs-0.2.0.820160904_ghc-8.0.1
#compiler-check: match-exact
#setup-info:
#  ghcjs:
#    source:
#      ghcjs-0.2.0.820170320_ghc-8.0.1:
#      ghcjs-0.2.0.820160904_ghc-8.0.1:
#         url: "http://tolysz.org/ghcjs/untested/ghc-8.0-2017-03-23-lts-8.5-9008005.tar.gz"
#         sha1: "cf4383b77f9d712133bdf54e6389c4361c57b484"
#allow-newer: true

packages:
- .
- ../lnotes-ui-core
- ../lnotes-ui-reactflux
- ../ln-sanitize
- ../ln-validate
- ../ln-api-ghcjs
- ../haskell-ln-types
- ../haskell-api-helpers-shared
- ../haskell-api-helpers-ghcjs
- ../haskell-either-helpers
- ../haskell-ebyam
- ../haskell-rehtie
- ../haskell-ifte
- ../haskell-web-bootstrap
- ../ghcjs-router
  #- ../ghcjs-ajax/ghcjs-ajax
- ../react-flux-router
- ../web-routes ## <-- remove if PR gets accepted

extra-deps:
- html-entities-1.1.4
- ref-tf-0.4
- these-0.6.1.0
- react-flux-1.1.1
- ghcjs-dom-0.2.4.0
